server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-catalog
info:
  app:
    name: api-catalog
    description: Catalogo of Movies

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka